### ISSUE TITLE
Latest problem with this: Module AppRegistry is not a callable module

### ISSUE THREAD

**Issue by IMakeTheSites** [iksena/RNWCShop#1]
Hi, so I've had several problems with your code. Some of these I noticed by checking your repo against what you wrote in your article on Medium.com and found discrepancies between the two; others were with your file naming and placement (product.component.tsx vs product.tsx). Following that, I had tons of problems with the shim.js file. First, I had to install, import, and require "process" on my own, second, I had to do the same when I had a "crypto" error.
Now my error gives me a blank white screen on both my simulators but the terminal tries to bundle index.js and fails with an error about AppRegistry. 
![Screen Shot 2021-01-15 at 11 28 49 PM](https://user-images.githubusercontent.com/13701540/104797100-9b259680-5789-11eb-9b41-115459bb4650.png)

**Comment by iksena** [comment]
Hi! Thank you for your feedback.
IMO file naming can be anything you want. The filenames are different from the tutorial because this repo is another way to learn building a shop app with RN. You can either choose to follow the article step-by-step or clone this repo directly and learn on your own.
The thing with the shim file and rn-nodeify is very tricky. It works by modifying the installed node modules to be compilable by RN. I usually just try removing node_modules and reinstalling then run the rn-nodeify again. You can follow the official documentation to customize it https://github.com/tradle/rn-nodeify
